server:
  port: 8088
  servlet:
    context-path: "" # 应用的上下文路径

spring:
  application:
    name: spring-cloud-eureka-ribbon-hystrix-consumer

eureka:
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/swagger-ui.html