spring:
  application:
    name: spring-cloud-eureka-feign-upload-client

server:
  port: 8083
  servlet:
    context-path: "" # 应用的上下文路径


eureka:
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/swagger-ui.html