spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 8080

management:
  context-path: /admin

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/swagger-ui.html