spring:
  application:
    name: spring-cloud-eureka-feign-upload-consumer

server:
  port: 8084
  servlet:
    context-path: "" # 应用的上下文路径


eureka:
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/swagger-ui.html

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000