server:
  port: 8086
  servlet:
    context-path: "" # 应用的上下文路径

spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      name: server.passport
      profile: development
      label: master

eureka:
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/swagger-ui.html