server:
  port: 8085
  servlet:
    context-path: "" # 应用的上下文路径

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    # 服务注册中心相关信息
    config:
      server:
        git:
          uri: git@gitlab.com:liangzai_cool/config-repo-{application}.git

eureka:
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/swagger-ui.html