server:
  port: 8088
spring:
  application:
    name: spring-cloud-eureka-ribbon-hystrix-consumer

management:
  context-path: /admin

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/swagger-ui.html