server:
  port: 8087
spring:
  application:
    name: spring-cloud-config-refreshable-client
  cloud:
    config:
      name: server.passport
      profile: development
      label: master

management:
  context-path: /admin

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/swagger-ui.html